# Generated by Django 5.1 on 2024-09-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_groups_persons_memberships_groups_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='group',
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='person',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Memberships',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
